#!/usr/bin/env bash
# Write docker-compose.override.yml sized to this machine. An override, not an edit: compose
# merges it automatically and git never sees a machine-specific diff.
set -euo pipefail
cd "$(dirname "$0")/.."

CORES=$(nproc)
TOTAL_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)

# Leave the host a quarter, or 1 GB, whichever is larger -- a cap above what the machine has
# bounds nothing. Under 4 GB reserve more, not less: no swap to absorb a spike.
if [ "$TOTAL_MB" -lt 4096 ]; then
    RESERVE_MB=$(( TOTAL_MB * 2 / 5 ))
else
    RESERVE_MB=$(( TOTAL_MB / 4 ))
fi
[ "$RESERVE_MB" -lt 1024 ] && RESERVE_MB=1024
LIMIT_MB=$(( TOTAL_MB - RESERVE_MB ))
[ "$LIMIT_MB" -lt 1536 ] && LIMIT_MB=1536

# /dev/shm carries pandarallel's pickled chunks and counts against the cap, so take a slice of
# it: 64 MB is what fails, not 1.5 GB is what is needed.
SHM_MB=$(( LIMIT_MB / 4 ))
[ "$SHM_MB" -gt 1024 ] && SHM_MB=1024
[ "$SHM_MB" -lt 256 ] && SHM_MB=256

# Each worker costs ~50 MB on top of the ~1 GB a job holds, so on a small machine the worker
# count is bounded by memory, not by cores.
WORKERS=$CORES
[ "$WORKERS" -gt 8 ] && WORKERS=8
BY_MEMORY=$(( (LIMIT_MB - 1024) / 256 ))
[ "$BY_MEMORY" -lt 1 ] && BY_MEMORY=1
[ "$WORKERS" -gt "$BY_MEMORY" ] && WORKERS=$BY_MEMORY

cat > docker-compose.override.yml <<YAML
# Generated by ubuntu_utils/03-size-for-this-machine.sh on $(hostname) -- ${CORES} cores, ${TOTAL_MB} MB RAM.
# Regenerate rather than edit; compose merges this over docker-compose.yml.
services:
  tauso-web:
    mem_limit: ${LIMIT_MB}m
    shm_size: ${SHM_MB}m
    environment:
      - TAUSO_CORES=${WORKERS}
      - TAUSO_MEMORY_MB=${LIMIT_MB}
YAML

echo "Wrote docker-compose.override.yml"
echo "  detected      ${CORES} cores, ${TOTAL_MB} MB RAM"
echo "  mem_limit     ${LIMIT_MB}m"
echo "  shm_size      ${SHM_MB}m   (at Docker's 64 MB default, feature calculation dies with"
echo "                              'No space left on device' while the disk is empty)"
echo "  TAUSO_CORES   ${WORKERS}"
