#!/usr/bin/env bash
# Write docker-compose.override.yml sized to this machine's CPU and RAM.
#
# An override rather than an edit to docker-compose.yml: the tracked file stays as the production
# box has it, compose merges this on top automatically, and git never sees a machine-specific diff.
set -euo pipefail
cd "$(dirname "$0")/.."

CORES=$(nproc)
TOTAL_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)

# Leave the host a quarter of the machine, or 1 GB, whichever is larger: a cap above what the
# machine has does not bound anything -- the kernel OOM killer fires first and takes whatever it
# likes, including processes outside the container.
RESERVE_MB=$(( TOTAL_MB / 4 ))
[ "$RESERVE_MB" -lt 1024 ] && RESERVE_MB=1024
LIMIT_MB=$(( TOTAL_MB - RESERVE_MB ))
[ "$LIMIT_MB" -lt 1536 ] && LIMIT_MB=1536

# /dev/shm only carries pandarallel's pickled chunks, and it counts against the cap above, so it
# is a slice of it rather than half: 64 MB is what fails, not 1.5 GB is what is needed.
SHM_MB=$(( LIMIT_MB / 4 ))
[ "$SHM_MB" -gt 1024 ] && SHM_MB=1024
[ "$SHM_MB" -lt 256 ] && SHM_MB=256

# Workers are process-parallel and each costs ~50 MB, on top of the ~1 GB a job holds anyway.
# Past the knee they buy little -- the machine's clock throttling caps the speedup near 3x -- so
# on a small machine the core count is bounded by memory rather than by cores.
WORKERS=$CORES
[ "$WORKERS" -gt 8 ] && WORKERS=8
BY_MEMORY=$(( (LIMIT_MB - 1024) / 256 ))
[ "$BY_MEMORY" -lt 1 ] && BY_MEMORY=1
[ "$WORKERS" -gt "$BY_MEMORY" ] && WORKERS=$BY_MEMORY

cat > docker-compose.override.yml <<YAML
# Generated by ubuntu_utils/03-size-for-this-machine.sh on $(hostname) -- ${CORES} cores, ${TOTAL_MB} MB RAM.
# Regenerate rather than edit; compose merges this over docker-compose.yml.
services:
  tauso-web:
    mem_limit: ${LIMIT_MB}m
    shm_size: ${SHM_MB}m
    environment:
      - TAUSO_CORES=${WORKERS}
      - TAUSO_MEMORY_MB=${LIMIT_MB}
YAML

echo "Wrote docker-compose.override.yml"
echo "  detected      ${CORES} cores, ${TOTAL_MB} MB RAM"
echo "  mem_limit     ${LIMIT_MB}m"
echo "  shm_size      ${SHM_MB}m   (at Docker's 64 MB default, feature calculation dies with"
echo "                              'No space left on device' while the disk is empty)"
echo "  TAUSO_CORES   ${WORKERS}"
