#!/usr/bin/env bash
# Write docker-compose.override.yml sized to this machine's CPU and RAM.
#
# An override rather than an edit to docker-compose.yml: the tracked file stays as the production
# box has it, compose merges this on top automatically, and git never sees a machine-specific diff.
set -euo pipefail
cd "$(dirname "$0")/.."

CORES=$(nproc)
TOTAL_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)

# Leave the host ~2 GB. A job holds well under 1 GB, so the cap is headroom, not a target.
LIMIT_MB=$(( TOTAL_MB - 2048 ))
[ "$LIMIT_MB" -lt 3072 ] && LIMIT_MB=3072
SHM_MB=$(( LIMIT_MB / 2 ))

# Workers are process-parallel and each costs ~50 MB; past the knee they buy little, and the
# machine's own clock throttling caps the speedup near 3x whatever the core count.
WORKERS=$CORES
[ "$WORKERS" -gt 8 ] && WORKERS=8

cat > docker-compose.override.yml <<YAML
# Generated by ubuntu_utils/03-size-for-this-machine.sh on $(hostname) -- ${CORES} cores, ${TOTAL_MB} MB RAM.
# Regenerate rather than edit; compose merges this over docker-compose.yml.
services:
  tauso-web:
    mem_limit: ${LIMIT_MB}m
    shm_size: ${SHM_MB}m
    environment:
      - TAUSO_CORES=${WORKERS}
      - TAUSO_MEMORY_MB=${LIMIT_MB}
YAML

echo "Wrote docker-compose.override.yml"
echo "  detected      ${CORES} cores, ${TOTAL_MB} MB RAM"
echo "  mem_limit     ${LIMIT_MB}m"
echo "  shm_size      ${SHM_MB}m   (at Docker's 64 MB default, feature calculation dies with"
echo "                              'No space left on device' while the disk is empty)"
echo "  TAUSO_CORES   ${WORKERS}"
